# Generated by Django 5.0.7 on 2024-07-12 07:56

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimages',
            name='image',
            field=models.ImageField(upload_to='room_images/', validators=[core.validators.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[core.validators.validate_image_format]),
        ),
    ]
